apiVersion: v1
kind: Pod
metadata:
  name: tomcatapp
  labels:
    app: tomcatapp
spec:
  containers:
  - name: tomcat
    image: gomathi747/cicd:latest 
    ports:
    - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatappsvc
spec:
  type: NodePort
  selector:
    app: tomcatapp
  ports:
  - port: 80
    targetPort: 8080
